# ---------- Build ----------
    FROM eclipse-temurin:21-jdk AS build
    WORKDIR /app
    
    COPY pom.xml .
    COPY mvnw .
    COPY mvnw.cmd .
    COPY .mvn/ .mvn/
    
    RUN chmod +x mvnw && ./mvnw -B -q -DskipTests dependency:go-offline
    
    COPY src ./src
    RUN ./mvnw -B -DskipTests package
    
    # ---------- Runtime ----------
    FROM eclipse-temurin:21-jre
    WORKDIR /work
    COPY --from=build /app/target/quarkus-app/ /work/
    EXPOSE 8080
    ENTRYPOINT ["java","-jar","/work/quarkus-run.jar"]
    