route:
  receiver: 'default'
  group_by: [ 'alertname' ]
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 2h
  routes:
    - matchers:
        - severity = 'critical'
      receiver: 'slack-email'

receivers:
  - name: 'default'
  - name: 'slack-email'
    slack_configs:
      - send_resolved: true
        api_url: '__SLACK_WEBHOOK__'
        channel: '#alerts'
        title: 'ALERTA {{ .Status }}: {{ .CommonLabels.alertname }}'
        text: |
          Detalles:
          {{ range .Alerts }}• {{ .Annotations.summary }} ({{ .Labels.severity }})
          {{ end }}
    email_configs:
      - to: '__ALERT_EMAILS__'
        from: '__SMTP_FROM__'
        smarthost: '__SMTP_HOST__:587'
        auth_username: '__SMTP_USER__'
        auth_identity: '__SMTP_USER__'
        auth_password: '__SMTP_PASS__'


