groups:
  - name: app-alerts
    rules:
      - alert: HostCPUHigh
        expr: 100 - (avg by(instance)(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 70
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "CPU del host > 70% durante 5 minutos"

      - alert: BackendAvailabilityLow
        expr: avg_over_time(probe_success{job="blackbox-http"}[5m]) < 0.95
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disponibilidad HTTP < 95% en los últimos 5 minutos"

      - alert: BackendLatencyHighP95
        expr: histogram_quantile(0.95, sum(rate(probe_http_duration_seconds_bucket{job="blackbox-http"}[5m])) by (le, instance)) > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "p95 HTTP > 1s durante 10 minutos"

      - alert: BackendMemoryHigh
        expr: max by(name) (container_memory_usage_bytes{name=~"app_(dev|uat|prod)"}) > 600000000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Memoria backend > ~600MB"


