global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'alertmanager:9093' ]

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'node'
    static_configs:
      - targets: [ 'localhost:9100' ]  # node-exporter in host network

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
      - targets:
          - http://host.docker.internal:8080/api/servicios
          - http://host.docker.internal:8080/api/page-content/home
          - http://host.docker.internal:3001/api/servicios
          - http://host.docker.internal:3001/api/page-content/home
          - http://host.docker.internal:3002/api/servicios
          - http://host.docker.internal:3002/api/page-content/home
          - http://host.docker.internal:3003/api/servicios
          - http://host.docker.internal:3003/api/page-content/home
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115


