apiVersion: 1
groups:
  - orgId: 1
    name: AppAlerts
    folder: Alerts
    interval: 1m
    rules:
      - uid: grafana_high_cpu
        title: Host CPU > 70%
        condition: A
        data:
          - refId: A
            datasourceUid: PROMDS
            model:
              editorMode: code
              expr: 100 - (avg by(instance)(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
              intervalMs: 60000
              legendFormat: CPU%
              maxDataPoints: 43200
              queryType: timeSeriesQuery
        for: 5m
        annotations:
          summary: CPU del host > 70% por 5m
        labels:
          severity: critical
        isPaused: false

      - uid: grafana_http_p95
        title: HTTP p95 > 1s
        condition: A
        data:
          - refId: A
            datasourceUid: PROMDS
            model:
              editorMode: code
              expr: histogram_quantile(0.95, sum(rate(probe_http_duration_seconds_bucket[5m])) by (le))
              intervalMs: 60000
              legendFormat: p95
              maxDataPoints: 43200
              queryType: timeSeriesQuery
        for: 10m
        annotations:
          summary: p95 HTTP > 1s (10m)
        labels:
          severity: critical
        isPaused: false

      - uid: grafana_http_availability
        title: HTTP Availability < 90%
        condition: A
        data:
          - refId: A
            datasourceUid: PROMDS
            model:
              editorMode: code
              expr: avg_over_time(probe_success{job="blackbox-http"}[5m])
              intervalMs: 60000
              legendFormat: success
              maxDataPoints: 43200
              queryType: timeSeriesQuery
        for: 5m
        annotations:
          summary: Disponibilidad HTTP < 90% (5m)
        labels:
          severity: critical
        isPaused: false

      - uid: grafana_backend_memory
        title: Backend Memory > 500MB
        condition: A
        data:
          - refId: A
            datasourceUid: PROMDS
            model:
              editorMode: code
              expr: container_memory_usage_bytes{container_label_io_kubernetes_container_name="backend"}
              intervalMs: 60000
              legendFormat: mem
              maxDataPoints: 43200
              queryType: timeSeriesQuery
        for: 10m
        annotations:
          summary: Memoria backend > ~500MB (10m)
        labels:
          severity: warning
        isPaused: false


